### ISSUE TITLE
searches are not supported as valid items

### ISSUE THREAD

**Issue by gpavinteractiv** [emmanuel-benoit/graylog-groups#1]
Hello,

- first thank you very much for this tool, it is extremely useful!

- I would like to give access to custom searches, those are sharable, as streams & dashboards, and accessible at the following urls : gaylogserver/search/UUID

I tried to add them to the yml config but got this error :
level=fatal msg="Invalid Graylog item" application=graylog component=graylog-groups config=./graylog-groups.yml entry=1 group="cn=appteam,cn=groups,cn=accounts,dc=hostics,dc=fr" item=search

It would be great  if you could add support for attributing rights on Searches too, as for Dashboards and Streams

**Comment by emmanuel-benoit** [comment]
Hello,
Thank you :)

We do not use shared saved searches here, so I didn't have the time to properly test it, but I have added some code that should do the trick. Could you please get back to me to tell me if it works for your use case ?

**Comment by gpavinteractiv** [comment]
I upgraded and it is working for us.
Thanks again
